---
title: "Untitled"
author: "Jose Gomez"
date: "2023-10-12"
output: html_document
---

# Weather Data Analysis

```{r load_library}
library(tidyverse)
```

```{r Read in data}
sf_weather <- read.csv("../raw_data/sf_weather_2023.csv")
head(sf_weather)
colnames(sf_weather)
```
```{r}
select(sf_weather, DATE)
date<-sf_weather %>%
  select(DATE)
```

```{r Subset and split out data}
sf_weather_temp <- sf_weather %>%
  select(c("DATE", "TMAX", "TMIN")) %>%
  na.omit() %>%
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep="-", remove= FALSE) %>%
  filter(YEAR == "2021") %>%
  mutate(TAVG = ( (TMAX + TMIN)/2) ) %>%
  group_by(MONTH) %>%
  summarize(MAX_MO_TEMP =max(TAVG))



print(sf_weather_temp)
```

```{r Plotting our data}
plot(sf_weather_temp)
```

```{r Apply functions}
yearly_subsetter <-function(year){
  year_subset <- sf_weather %>%
  select(c("DATE", "TMAX", "TMIN")) %>%
  na.omit() %>%
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep="-", remove= FALSE) %>%
  filter(YEAR == year) %>%
  mutate(TAVG = ( (TMAX + TMIN)/2) ) %>%
  group_by(MONTH) %>%
  summarize(MAX_MO_TEMP =max(TAVG))
  
  return(year_subset)
}

yearly_subsetter("2020")
```

```{r}
year_var<- "1980"

plot(yearly_subsetter(year=year_var) , main = year_var)

```

```{r Apply function with loops}
for(my_year_var in c("1970", "1980", "1990", "2000")) {
  plot(yearly_subsetter(year =my_year_var), main =my_year_var)
}

```






